version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx/
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - app-network
    volumes:
      - wp_data:/var/www/html

  mariadb:
    build:
      context: ./requirements/mariadb/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s

  wordpress:
    build:
      context: ./requirements/wordpress/
    expose:
      - "9000"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network
    environment:
      DB_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    volumes:
      - wp_data:/var/www/html
    restart: always

volumes:
  db_data:
  wp_data:


networks:
  app-network:
